const TeamFortress2 = require('./index.js');

TeamFortress2.GCGoodbyeReason = {
	GC_GOING_DOWN: 1,
	NO_SESSION: 2
};

TeamFortress2.TradeResponse = {
	Accepted: 0,
	Declined: 1,
	TradeBannedInitiator: 2,
	TradeBannedTarget: 3,
	TargetAlreadyTrading: 4,
	Disabled: 5,
	NotLoggedIn: 6,
	Cancel: 7,
	TooSoon: 8,
	TooSoonPenalty: 9,
	ConnectionFailed: 10,
	AlreadyTrading: 11,
	AlreadyHasTradeRequest: 12,
	NoResponse: 13,
	CyberCafeInitiator: 14,
	CyberCafeTarget: 15,
	SchoolLabInitiator: 16,
	SchoolLabTarget: 16,
	InitiatorBlockedTarget: 18,
	InitiatorNeedsVerifiedEmail: 20,
	InitiatorNeedsSteamGuard: 21,
	TargetAccountCannotTrade: 22,
	InitiatorSteamGuardDuration: 23,
	InitiatorPasswordResetProbation: 24,
	InitiatorNewDeviceCooldown: 25,
	OKToDeliver: 50
};

TeamFortress2.Class = {
	Scout: 1,
	Sniper: 2,
	Soldier: 3,
	Demoman: 4,
	Medic: 5,
	Heavy: 6,
	Pyro: 7,
	Spy: 8,
	Engineer: 9
};

TeamFortress2.ItemSlot = {
	Primary: 0,
	Secondary: 1,
	Melee: 2,
	// 3 appears to be unused
	Sapper: 4, // Sapper
	PDA: 5,
	PDA2: 6,
	Cosmetic1: 7,
	Cosmetic2: 8,
	Action: 9,
	Cosmetic3: 10,
	Taunt1: 11,
	Taunt2: 12,
	Taunt3: 13,
	Taunt4: 14,
	Taunt5: 15,
	Taunt6: 16,
	Taunt7: 17,
	Taunt8: 18
};

TeamFortress2.ItemFlags = {
	CannotTrade: (1 << 0),
	CannotCraft: (1 << 1),
	NotEcon: (1 << 3),
	Preview: (1 << 7)
};

TeamFortress2.War = {
	HeavyVsPyro: 0
};

TeamFortress2.HeavyVsPyroWarSide = {
	Heavy: 0,
	Pyro: 1
};

TeamFortress2.CraftRecipes = {
	"Smelt Class Weapons": 3,
  "Combine Scrap Metal": 4,
  "Combine Reclaimed Metal": 5,
  "Fabricate Headgear": 6,
  "Fabricate Class Token": 7,
  "Fabricate Slot Token": 8,
  "Rebuild Headgear": 9,
  "Fabricate Class Headgear": 10,
  "Fabricate Class Weapon": 11,
  "Rebuild Class Token": 13,
  "Rebuild Slot Token": 14,
  "Smelt Tokens": 15,
  "Fabricate Bonk Helm": 16,
  "Fabricate Crit-a-Cola": 17,
  "Fabricate The Pain Train": 18,
  "Fabricate The Gunboats": 19,
  "Fabricate The Dalokohs Bar": 20,
  "Fabricate The Homewrecker": 21,
  "Smelt Reclaimed Metal": 22,
  "Smelt Refined Metal": 23,
  "Fabricate The Scotsman's Skullcutter": 24,
  "Fabricate The Tribalman's Shiv": 25,
  "Fabricate The Southern Hospitality": 26,
  "Fabricate The Powerjack": 27,
  "Fabricate The Degreaser": 28,
  "Fabricate The Shortstop": 29,
  "Fabricate The Holy Mackerel": 30,
  "Fabricate Mad Milk": 31,
  "Fabricate L'Etranger": 32,
  "Fabricate Your Eternal Reward": 33,
  "Fabricate The Battalion's Backup": 34,
  "Fabricate The Black Box": 35,
  "Fabricate The Sydney Sleeper": 36,
  "Fabricate Darwin's Danger Shield": 37,
  "Fabricate The Bushwacka": 38,
  "Fabricate Gloves of Running Urgently": 39,
  "Fabricate The Vita-Saw": 40,
  "Fabricate Set Headgear": 41,
  "Halloween Mask - Saxton Hale": 42,
  "The Horseless Headless Horseman's Headtaker": 43,
  "Haunted Hat": 44,
  "Fabricate The Amputator": 45,
  "Fabricate The Crusader's Crossbow": 46,
  "Fabricate The Ullapool Caber": 47,
  "Fabricate The Loch-n-Load": 48,
  "Fabricate Warrior's Spirit": 49,
  "Fabricate The Buffalo Steak Sandvich": 50,
  "Fabricate The Brass Beast": 51,
  "Fabricate The Candy Cane": 52,
  "Fabricate The Claidheamohmor": 53,
  "Fabricate The Back Scratcher": 54,
  "Fabricate The Boston Basher": 55,
  "Fabricate Fists of Steel": 56,
  "Fabricate The Jag": 57,
  "Fabricate The Axtinguisher": 58,
  "Fabricate Sun-on-a-Stick": 59,
  "Fabricate The Half-Zatoichi": 60,
  "Fabricate The Concheror": 61,
  "Fabricate Conniver's Kunai": 62,
  "Fabricate The Fan O'War": 63,
  "Fishcake": 64,
  "SpaceChem Pin": 65,
  "Fabricate The Soda Popper": 66,
  "Fabricate The Winger": 67,
  "Fabricate The Atomizer": 68,
  "Fabricate The Family Business": 69,
  "Fabricate Tomislav": 70,
  "Fabricate The Eviction Notice": 71,
  "Fabricate The Enforcer": 72,
  "Fabricate The Big Earner": 73,
  "Fabricate The Bazaar Bargain": 74,
  "Fabricate The Shahanshah": 75,
  "Fabricate The Persian Persuader": 76,
  "Fabricate The Splendid Screen": 77,
  "Fabricate Ali Baba's Wee Booties": 78,
  "Fabricate The Liberty Launcher": 79,
  "Fabricate The Reserve Shooter": 80,
  "Fabricate The Market Gardener": 81,
  "Fabricate The Mantreads": 82,
  "Fabricate The Disciplinary Action": 83,
  "Fabricate The Detonator": 84,
  "Fabricate The Overdose": 85,
  "Fabricate The Solemn Vow": 86,
  "Fabricate The Quick-Fix": 87,
  "Fabricate The Cow Mangler 5000": 88,
  "Fabricate The Righteous Bison": 89,
  "Fabricate The Diamondback": 90,
  "Fabricate The Machina": 91,
  "Fabricate The Widowmaker": 92,
  "Fabricate The Short Circuit": 93,
  "Fabricate The Original": 94,
  "Fabricate The Spy-Cicle": 95,
  "Fabricate The Holiday Punch": 96,
  "Fabricate The Wrap Assassin": 97,
  "Fabricate The Phlogistinator": 98,
  "Fabricate The Manmelter": 99,
  "Fabricate The Third Degree": 100,
  "Fabricate The Pomson 6000": 101,
  "Fabricate The Eureka Effect": 102,
  "Fabricate The Cozy Camper": 103,
  "Fabricate The Escape Plan": 104,
  "Pile Of Ash": 105,
  "Fabricate The Beggar's Bazooka": 106,
  "Fabricate The Hitman's Heatmaker": 107,
  "Fabricate The Cleaner's Carbine": 108,
  "Fabricate Baby Face's Blaster": 109,
  "Fabricate Pretty Boy's Pocket Pistol": 110,
  "Fabricate The Scorch Shot": 111,
  "Fabricate The Neon Annihilator": 112,
  "Fabricate The Flying Guillotine": 113,
  "Fabricate The Huo Long Heatmaker": 114,
  "Fabricate The Red-Tape Recorder": 115,
  "Power Up Canteen": 116,
  "Pile Of Curses": 117,
  "Fabricate The Rescue Ranger": 118,
  "Fabricate The Loose Cannon": 119,
  "Fabricate The Vaccinator": 120,
  "Fabricate Stickybomb Jumper": 121,
  "Fabricate Rocket Jumper": 122,
  "Fabricate The Air Strike": 123,
  "Fabricate The Tide Turner": 124,
  "Fabricate The B.A.S.E. Jumper": 125,
  "Fabricate The Classic": 126,
  "Fabricate The Back Scatter": 127,
  "Fabricate Panic Attack Shotgun": 128,
  "Fabricate The Iron Bomber": 129,
  "Fabricate The Quickiebomb Launcher": 130,
  "Giftapult Gift Wrap": 131,
  "Strange Count Transfer Tool": 132,

  // Value-to-name mapping for convenience
  "3": "Smelt Class Weapons",
  "4": "Combine Scrap Metal",
  "5": "Combine Reclaimed Metal",
  "6": "Fabricate Headgear",
  "7": "Fabricate Class Token",
  "8": "Fabricate Slot Token",
  "9": "Rebuild Headgear",
  "10": "Fabricate Class Headgear",
  "11": "Fabricate Class Weapon",
  "13": "Rebuild Class Token",
  "14": "Rebuild Slot Token",
  "15": "Smelt Tokens",
  "16": "Fabricate Bonk Helm",
  "17": "Fabricate Crit-a-Cola",
  "18": "Fabricate The Pain Train",
  "19": "Fabricate The Gunboats",
  "20": "Fabricate The Dalokohs Bar",
  "21": "Fabricate The Homewrecker",
  "22": "Smelt Reclaimed Metal",
  "23": "Smelt Refined Metal",
  "24": "Fabricate The Scotsman's Skullcutter",
  "25": "Fabricate The Tribalman's Shiv",
  "26": "Fabricate The Southern Hospitality",
  "27": "Fabricate The Powerjack",
  "28": "Fabricate The Degreaser",
  "29": "Fabricate The Shortstop",
  "30": "Fabricate The Holy Mackerel",
  "31": "Fabricate Mad Milk",
  "32": "Fabricate L'Etranger",
  "33": "Fabricate Your Eternal Reward",
  "34": "Fabricate The Battalion's Backup",
  "35": "Fabricate The Black Box",
  "36": "Fabricate The Sydney Sleeper",
  "37": "Fabricate Darwin's Danger Shield",
  "38": "Fabricate The Bushwacka",
  "39": "Fabricate Gloves of Running Urgently",
  "40": "Fabricate The Vita-Saw",
  "41": "Fabricate Set Headgear",
  "42": "Halloween Mask - Saxton Hale",
  "43": "The Horseless Headless Horseman's Headtaker",
  "44": "Haunted Hat",
  "45": "Fabricate The Amputator",
  "46": "Fabricate The Crusader's Crossbow",
  "47": "Fabricate The Ullapool Caber",
  "48": "Fabricate The Loch-n-Load",
  "49": "Fabricate Warrior's Spirit",
  "50": "Fabricate The Buffalo Steak Sandvich",
  "51": "Fabricate The Brass Beast",
  "52": "Fabricate The Candy Cane",
  "53": "Fabricate The Claidheamohmor",
  "54": "Fabricate The Back Scratcher",
  "55": "Fabricate The Boston Basher",
  "56": "Fabricate Fists of Steel",
  "57": "Fabricate The Jag",
  "58": "Fabricate The Axtinguisher",
  "59": "Fabricate Sun-on-a-Stick",
  "60": "Fabricate The Half-Zatoichi",
  "61": "Fabricate The Concheror",
  "62": "Fabricate Conniver's Kunai",
  "63": "Fabricate The Fan O'War",
  "64": "Fishcake",
  "65": "SpaceChem Pin",
  "66": "Fabricate The Soda Popper",
  "67": "Fabricate The Winger",
  "68": "Fabricate The Atomizer",
  "69": "Fabricate The Family Business",
  "70": "Fabricate Tomislav",
  "71": "Fabricate The Eviction Notice",
  "72": "Fabricate The Enforcer",
  "73": "Fabricate The Big Earner",
  "74": "Fabricate The Bazaar Bargain",
  "75": "Fabricate The Shahanshah",
  "76": "Fabricate The Persian Persuader",
  "77": "Fabricate The Splendid Screen",
  "78": "Fabricate Ali Baba's Wee Booties",
  "79": "Fabricate The Liberty Launcher",
  "80": "Fabricate The Reserve Shooter",
  "81": "Fabricate The Market Gardener",
  "82": "Fabricate The Mantreads",
  "83": "Fabricate The Disciplinary Action",
  "84": "Fabricate The Detonator",
  "85": "Fabricate The Overdose",
  "86": "Fabricate The Solemn Vow",
  "87": "Fabricate The Quick-Fix",
  "88": "Fabricate The Cow Mangler 5000",
  "89": "Fabricate The Righteous Bison",
  "90": "Fabricate The Diamondback",
  "91": "Fabricate The Machina",
  "92": "Fabricate The Widowmaker",
  "93": "Fabricate The Short Circuit",
  "94": "Fabricate The Original",
  "95": "Fabricate The Spy-Cicle",
  "96": "Fabricate The Holiday Punch",
  "97": "Fabricate The Wrap Assassin",
  "98": "Fabricate The Phlogistinator",
  "99": "Fabricate The Manmelter",
  "100": "Fabricate The Third Degree",
  "101": "Fabricate The Pomson 6000",
  "102": "Fabricate The Eureka Effect",
  "103": "Fabricate The Cozy Camper",
  "104": "Fabricate The Escape Plan",
  "105": "Pile Of Ash",
  "106": "Fabricate The Beggar's Bazooka",
  "107": "Fabricate The Hitman's Heatmaker",
  "108": "Fabricate The Cleaner's Carbine",
  "109": "Fabricate Baby Face's Blaster",
  "110": "Fabricate Pretty Boy's Pocket Pistol",
  "111": "Fabricate The Scorch Shot",
  "112": "Fabricate The Neon Annihilator",
  "113": "Fabricate The Flying Guillotine",
  "114": "Fabricate The Huo Long Heatmaker",
  "115": "Fabricate The Red-Tape Recorder",
  "116": "Power Up Canteen",
  "117": "Pile Of Curses",
  "118": "Fabricate The Rescue Ranger",
  "119": "Fabricate The Loose Cannon",
  "120": "Fabricate The Vaccinator",
  "121": "Fabricate Stickybomb Jumper",
  "122": "Fabricate Rocket Jumper",
  "123": "Fabricate The Air Strike",
  "124": "Fabricate The Tide Turner",
  "125": "Fabricate The B.A.S.E. Jumper",
  "126": "Fabricate The Classic",
  "127": "Fabricate The Back Scatter",
  "128": "Fabricate Panic Attack Shotgun",
  "129": "Fabricate The Iron Bomber",
  "130": "Fabricate The Quickiebomb Launcher",
  "131": "Giftapult Gift Wrap",
  "132": "Strange Count Transfer Tool"
}
